-- COMMAND LIMIT OVERRIDES
NDefines.NMilitary.CORPS_COMMANDER_DIVISIONS_CAP = 1000
NDefines.NMilitary.FIELD_MARSHAL_DIVISIONS_CAP = 1000
NDefines.NMilitary.FIELD_MARSHAL_ARMIES_CAP = 1000

-- NAVAL INVASION OVERRIDES (Bypass All Checks)
NDefines.NNavy.NAVAL_INVASION_SUPREMACY_REQUIREMENT = 0.001
NDefines.NNavy.MIN_SUPREMACY_FOR_INVASION = 0.001
NDefines.NNavy.SUPREMACY_NEEDED_FOR_INVASION = 0.001
NDefines.NMilitary.NAVAL_INVASION_PREPARATION_DAYS_BASE = 0
NDefines.NMilitary.NAVAL_INVASION_PREPARATION_DAYS_PER_DIVISION = 0
NDefines.NMilitary.AMPHIBIOUS_INVADE_SPEED_BASE = 10.0
NDefines.NMilitary.AMPHIBIOUS_INVADE_MOVEMENT_COST = 0.1